api:
    path: /api
    controller: App\Controller\AuthenticationController::api
    methods:  [GET]
login_check:
    path: /login_check
    methods: [POST]
gesdinet_jwt_refresh_token:
    path:       /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
